### ISSUE TITLE
Issue with the ohlcv() call

### ISSUE THREAD

**Issue by ghost** [bizzyvinci/cmc-api#1]
Hi,

Am I doing something wrong when trying to make the ohlcv() call? Thank you!

```
from cmc_api import CoinMarketCap

cmc = CoinMarketCap(CMC_API_KEY)
# works
x = cmc.quotes(slug='safemoon')

# fails: AttributeError: 'CoinMarketCap' object has no attribute 'ohlcv'
y = cmc.ohlcv()

# Also tried
y = cmc.ohlcv(slug='safemoon')
```

**Comment by bizzyvinci** [comment]
I guess you must have installed using `pip install cmc-api`.

Unfortunately, ohlcv method was not included in the last pypi release. To use the latest commit, install using `pip install -U git+https://github.com/bizzyvinci/cmc-api.git` and let me know how it goes.

I would add some things and make a new release this week. Thanks.

**Comment by ghost** [comment]
This allows me to make the ohlcv() call but it turns out the basic subscription plan does not allow for obtaining that data.

Thank you for your prompt reply!

**Comment by bizzyvinci** [comment]
If you use `cmc = CoinMarketCap(root="web")`. You get access to all endpoint and parameters. I don't know if there's limitations but it works fine for basic scrapping.
